# Generated by Django 4.1.4 on 2022-12-28 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0002_doctors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('number', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('Booked_on', models.DateField(auto_now=True)),
                ('Doctor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.doctors')),
            ],
        ),
    ]
